[package]
name = "murder"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
nix = { version = "0.29", features = ["signal", "process"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "process", "sync"] }
